#!/usr/bin/env python3
"""Pull the break and the slice tables out of an Amenizer ROM as sdas source.

The reimplementation carries no audio of its own: the 16 KiB sample at
0x4000-0x7FFF and the 256-byte table block at 0x3F00-0x3FFF are copied from an
existing cartridge and pinned back at the same addresses, and the boot TMA is
read from 0x016A. Those are exactly what the web app patches, so any ROM it
has produced rebuilds from source with its own break, tables and rate.

It emits assembly rather than C because SDCC concatenates `__at` constants
from different modules into one _CABS area, which drops their addresses; an
ABS area of our own with explicit `.org`s does not.

usage: extract_assets.py <amenizer.gb> <out.s>
"""

import sys

ROM_SIZE = 0x8000
TABLES_BASE, TABLES_BYTES = 0x3F00, 0x100
SAMPLE_BASE, SAMPLE_BYTES = 0x4000, 0x4000
TMA_OFFSET = 0x016A
# `ld hl,$4000 / ld c,$30` at the top of the engine block (ROM 0x033F).
ENGINE_SIGNATURE = bytes([0x21, 0x00, 0x40, 0x0E, 0x30])


def block(name: str, addr: int, data: bytes) -> str:
    rows = [f"\t.org 0x{addr:04X}", f"_{name}::"]
    for i in range(0, len(data), 16):
        rows.append("\t.db " + ", ".join(f"0x{b:02X}" for b in data[i : i + 16]))
    return "\n".join(rows) + "\n"


def main() -> None:
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    rom = open(sys.argv[1], "rb").read()
    if len(rom) != ROM_SIZE:
        sys.exit(f"{sys.argv[1]}: expected {ROM_SIZE} bytes, got {len(rom)}")
    if rom[0x134:0x13C] != b"AMENIZER" or rom[0x33F:0x344] != ENGINE_SIGNATURE:
        sys.exit(f"{sys.argv[1]}: not an Amenizer ROM")

    out = [
        f"; Generated by rom/tools/extract_assets.py from {sys.argv[1].rsplit('/', 1)[-1]}"
        " -- do not edit.\n",
        "\t.area _AMENIZER_DATA (ABS)\n",
        "; 16 tables x 16 steps, index (table << 4) | step.",
        block("slice_tables", TABLES_BASE, rom[TABLES_BASE : TABLES_BASE + TABLES_BYTES]),
        "; 4-bit PCM, two samples per byte, high nibble first.",
        block("sample_data", SAMPLE_BASE, rom[SAMPLE_BASE : SAMPLE_BASE + SAMPLE_BYTES]),
        "\t.area _CODE\n",
        "; Boot TMA, the operand of `ld a,$ad` at 0x0169.",
        f"_boot_tma::\n\t.db 0x{rom[TMA_OFFSET]:02X}\n",
    ]
    with open(sys.argv[2], "w") as f:
        f.write("\n".join(out))


if __name__ == "__main__":
    main()
